<?php
/**@var Elogic\TestUnit\ViewModel\ProductListing $viewModel*/
$viewModel = $block->getData('viewModel');

// print current product data
$vendor_id = $block->getProduct()->getVendor();
$res_data = $viewModel->getVendorDescription($vendor_id);
?>
<?php if(isset($res_data['name'])) {
    ?>
    <h3>Vendor Name: <?= $res_data['name']; ?></h3>
    <span>Vendor Desrciprion: <?= $res_data['post_content']; ?></span>
<?php
}
?>


